server:
  host: "0.0.0.0"
  port: 5002

pipeline:
  layout:
    model_dir: "PaddlePaddle/PP-DocLayoutV3_safetensors"

  ocr_api:
    api_host: "localhost"
    api_port: 8081
    model: "glm-ocr"
    api_mode: "openai"
